use std::env;
use std::ffi::OsString;
use std::fs;
use std::io::ErrorKind;
use std::path::{Component, Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

/// Options for building a generated C++ project.
#[derive(Debug, Clone)]
pub struct BuildOptions {
    pub build_dir: PathBuf,
}

/// Options for building and running a generated C++ project.
#[derive(Debug, Clone)]
pub struct RunOptions {
    pub build_dir: PathBuf,
    pub target_name: Option<String>,
    pub program_args: Vec<String>,
}

/// Options for removing generated build artifacts.
#[derive(Debug, Clone)]
pub struct CleanOptions {
    pub build_dir: PathBuf,
}

/// Configure and build the current C++ project.
pub fn build_project(options: &BuildOptions) -> Result<()> {
    ensure_cmake_project()?;
    run_command(
        "cmake",
        [
            OsString::from("-S"),
            OsString::from("."),
            OsString::from("-B"),
            options.build_dir.as_os_str().to_owned(),
            OsString::from("-G"),
            OsString::from("Ninja"),
            OsString::from("-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"),
        ],
    )?;
    sync_compile_commands(&options.build_dir)?;
    run_command(
        "cmake",
        [
            OsString::from("--build"),
            options.build_dir.as_os_str().to_owned(),
            OsString::from("-j"),
        ],
    )
}

/// Configure, build, and run the current C++ project.
pub fn run_project(options: &RunOptions) -> Result<()> {
    build_project(&BuildOptions {
        build_dir: options.build_dir.clone(),
    })?;

    let target_name = match &options.target_name {
        Some(target_name) => validate_run_target_name(target_name)?,
        None => detect_first_executable_target(Path::new("CMakeLists.txt"))?,
    };

    let executable = executable_path(&options.build_dir, &target_name);
    if !executable.is_file() {
        bail!(
            "expected executable {} after build; pass --target if the CMake target name is different",
            executable.display()
        );
    }

    let status = Command::new(&executable)
        .args(&options.program_args)
        .status()
        .with_context(|| format!("failed to run {}", executable.display()))?;

    if !status.success() {
        bail!("{} exited with {status}", executable.display());
    }

    Ok(())
}

/// Remove the configured build directory and root compile_commands.json.
pub fn clean_project(options: &CleanOptions) -> Result<()> {
    ensure_cmake_project()?;
    validate_clean_build_dir(&options.build_dir)?;

    remove_path_if_exists(&options.build_dir)?;
    remove_compile_commands(Path::new("compile_commands.json"))?;
    println!(
        "Removed {} and compile_commands.json if they existed",
        options.build_dir.display()
    );

    Ok(())
}

fn ensure_cmake_project() -> Result<()> {
    if !Path::new("CMakeLists.txt").is_file() {
        bail!("CMakeLists.txt not found; run this command from a C++ project root");
    }

    Ok(())
}

fn run_command<I>(program: &str, args: I) -> Result<()>
where
    I: IntoIterator<Item = OsString>,
{
    let args: Vec<OsString> = args.into_iter().collect();
    let status = Command::new(program)
        .args(&args)
        .status()
        .with_context(|| format!("failed to start {program}; is it installed and on PATH?"))?;

    if !status.success() {
        bail!("{program} exited with {status}");
    }

    Ok(())
}

fn sync_compile_commands(build_dir: &Path) -> Result<()> {
    let source = build_dir.join("compile_commands.json");
    if !source.is_file() {
        bail!("{} was not generated by CMake", source.display());
    }

    let destination = Path::new("compile_commands.json");
    remove_compile_commands(destination)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;

        symlink(&source, destination)
            .or_else(|_| fs::copy(&source, destination).map(|_| ()))
            .with_context(|| {
                format!(
                    "failed to link or copy {} to {}",
                    source.display(),
                    destination.display()
                )
            })
    }

    #[cfg(not(unix))]
    {
        fs::copy(&source, destination).map(|_| ()).with_context(|| {
            format!(
                "failed to copy {} to {}",
                source.display(),
                destination.display()
            )
        })
    }
}

fn remove_compile_commands(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() => bail!("{} exists and is a directory", path.display()),
        Ok(_) => fs::remove_file(path)
            .with_context(|| format!("failed to remove existing {}", path.display())),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("failed to inspect {}", path.display())),
    }
}

fn remove_path_if_exists(path: &Path) -> Result<()> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() || metadata.is_file() => {
            fs::remove_file(path).with_context(|| format!("failed to remove {}", path.display()))
        }
        Ok(metadata) if metadata.is_dir() => {
            fs::remove_dir_all(path).with_context(|| format!("failed to remove {}", path.display()))
        }
        Ok(_) => {
            fs::remove_file(path).with_context(|| format!("failed to remove {}", path.display()))
        }
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error).with_context(|| format!("failed to inspect {}", path.display())),
    }
}

fn validate_clean_build_dir(build_dir: &Path) -> Result<()> {
    if build_dir.as_os_str().is_empty() {
        bail!("build directory cannot be empty");
    }

    if build_dir.is_absolute() {
        bail!("clean build directory must be relative to the project root");
    }

    if build_dir == Path::new(".") {
        bail!("refusing to clean the project root");
    }

    for component in build_dir.components() {
        match component {
            Component::Normal(_) => {}
            Component::CurDir => {}
            Component::ParentDir => bail!("clean build directory must not contain '..'"),
            Component::RootDir | Component::Prefix(_) => {
                bail!("clean build directory must be relative to the project root")
            }
        }
    }

    Ok(())
}

fn detect_first_executable_target(cmake_path: &Path) -> Result<String> {
    let cmake = fs::read_to_string(cmake_path)
        .with_context(|| format!("failed to read {}", cmake_path.display()))?;

    let Some(after_keyword) = cmake.split("add_executable").nth(1) else {
        bail!(
            "could not find an add_executable target in {}",
            cmake_path.display()
        );
    };

    let Some(after_open_paren) = after_keyword.split_once('(').map(|(_, rest)| rest) else {
        bail!("could not parse add_executable in {}", cmake_path.display());
    };

    let target_name = after_open_paren
        .trim_start()
        .split(|character: char| character.is_whitespace() || character == ')')
        .next()
        .unwrap_or_default()
        .trim_matches('"');

    validate_run_target_name(target_name)
}

fn validate_run_target_name(target_name: &str) -> Result<String> {
    if target_name.trim().is_empty() {
        bail!("target name cannot be empty");
    }

    if target_name.contains('/') || target_name.contains('\\') {
        bail!("target name must not contain path separators");
    }

    Ok(target_name.to_owned())
}

fn executable_path(build_dir: &Path, target_name: &str) -> PathBuf {
    let executable_name = if cfg!(windows) {
        format!("{target_name}.exe")
    } else {
        target_name.to_owned()
    };

    env::current_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(build_dir)
        .join(executable_name)
}
